name: qwen3-tts-api
services:
  qwen3-tts:
    image: ghcr.io/hsiang-han/qwen3-tts-api:latest
    container_name: qwen3-tts-api
    build:
      context: ../..
      dockerfile: docker/gpu/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - /mnt/user/appdata/qwen3-tts-api/models:/root/.cache/huggingface
    environment:
      - MODEL_ID=Qwen/Qwen3-TTS-12Hz-1.7B-CustomVoice
      - DTYPE=bfloat16
      - ATTN_IMPLEMENTATION=sdpa
      - HF_ENDPOINT=https://huggingface.co
      - PORT=8080
    shm_size: "4gb"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
